services:
  consumer:
    container_name: notification-consumer-email
    build:
      context: ./
      dockerfile: ../../docker/Dockerfile.dev
    working_dir: /app/notification/consumer-email
    command: air -c .air.toml
    volumes:
      - ../../:/app
      - $GOPATH/pkg/mod:/go/pkg/mod
    env_file:
      - .env.generated

  mailpit:
    image: axllent/mailpit:latest
    ports:
      - 8025:8025
    environment:
      - MP_SMTP_AUTH_ACCEPT_ANY=true
      - MP_SMTP_AUTH_ALLOW_INSECURE=true
