services:
  postgres:
    image: postgres:16.3
    environment:
      - POSTGRES_USER=auth
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=auth
    ports:
      - 5432:5432

  redis:
    image: redis:7.4
    ports:
      - 6379:6379
