services:
  server:
    container_name: auth-server-session
    build:
      context: ./
      dockerfile: ../../docker/Dockerfile.dev
    working_dir: /app/auth/server-session
    command: air -c .air.toml
    volumes:
      - ../../:/app
      - $GOPATH/pkg/mod:/go/pkg/mod
    ports:
      - 8080:8080
    env_file:
      - .env.generated
