export enum Module {
  LISTENING = 'LISTENING',
  READING = 'READING',
  WRITING = 'WRITING',
  SPEAKING = 'SPEAKING',
}

export enum Section {
  FULLTEST = 'FULLTEST',
  SECTIONTEST = 'SECTIONTEST',
}
